### PR TITLE
Support GraalVM 21.2.0

### PR DESCRIPTION
**Pull request by davidfrickert**

### CODE REVIEW

**Comment by findepi** [comment]
@davidfrickert many thanks for the PR!

according to https://www.graalvm.org/release-notes/21_2/, the release is not fully done yet, as the Java 8 build is marked as "coming soon"

> Java and Compiler Updates 
The OpenJDK release that GraalVM Community Edition is built on was updated to:
8u302 for Java 8 based GraalVM Community. See OpenJDK 8u302 Updates. Coming soon
11.0.12 for Java 11 based GraalVM Community. See OpenJDK 11.0.12 Updates
16.0.2 for Java 16 based GraalVM Community. See OpenJDK 16.0.2 Updates. Coming soon

Do you maybe have an idea what "soon" can actually mean here?

**Comment by davidfrickert** [comment]
Uhh I have no clue.
That is super weird indeed.

The Java8 & Java16 builds seem to not be available yet.

**Comment by findepi** [comment]
Seems like someone had "to release or not to release" dilemma and decided to have both ;)

Maybe we should follow the pattern then?
Temporarily drop the Java 8 version and add it back when it shows up on https://github.com/graalvm/graalvm-ce-builds/releases.

A bit of unnecessary work, but maybe that's still more useful than just waiting.
@davidfrickert wdyt?

**Comment by davidfrickert** [comment]
Yeah most likely they had an hard limit on release date but the other java versions were not ready. Oh well.
I think either that, or just leave as is and when they release the Java8 version the builds will start working again?
I'm not sure if they run automatically, but that could be an option to avoid having to manually disable and re-enable.

**Comment by davidfrickert** [comment]
I think this can be merged @findepi, seems like java 8 builds have been provided.
I don't know how to retry the failed build here on github but would be nice if possible just to be sure it works before merging.

**Comment by findepi** [comment]
Many thanks!

**Pull request merged**
